// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleApiSecret handles apiSecret security.
	// API secret key from Developer → API Keys.
	HandleApiSecret(ctx context.Context, operationName OperationName, t ApiSecret) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesApiSecret is a private map storing roles per operation.
var operationRolesApiSecret = map[string][]string{
	CreateAgentOperation:      []string{},
	CreateEmbedTokenOperation: []string{},
	CreateSessionOperation:    []string{},
	CreateVideoOperation:      []string{},
	CreateWebhookOperation:    []string{},
	DeleteAgentOperation:      []string{},
	DeleteWebhookOperation:    []string{},
	EndSessionOperation:       []string{},
	GetAgentOperation:         []string{},
	GetBalanceOperation:       []string{},
	GetSessionOperation:       []string{},
	GetVideoOperation:         []string{},
	ListAgentsOperation:       []string{},
	ListVoicesOperation:       []string{},
	ListWebhooksOperation:     []string{},
	SpeakOperation:            []string{},
	TextToSpeechOperation:     []string{},
	UpdateAgentOperation:      []string{},
	UploadFileOperation:       []string{},
	ValidateOperation:         []string{},
}

// GetRolesForApiSecret returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiSecret(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiSecret(operation string) []string {
	roles, ok := operationRolesApiSecret[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityApiSecret(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiSecret
	const parameterName = "api-secret"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesApiSecret[operationName]
	rctx, err := s.sec.HandleApiSecret(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiSecret provides apiSecret security value.
	// API secret key from Developer → API Keys.
	ApiSecret(ctx context.Context, operationName OperationName) (ApiSecret, error)
}

func (s *Client) securityApiSecret(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiSecret(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiSecret\"")
	}
	req.Header.Set("api-secret", t.APIKey)
	return nil
}
