// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Agent
type Agent struct {
	// Unique agent identifier.
	ID string `json:"id"`
	// Agent display name.
	Name OptString `json:"name"`
	// Agent generation status.
	Status AgentStatus `json:"status"`
	// Agent personality prompt.
	Prompt OptString `json:"prompt"`
	// Avatar model type.
	ModelType OptAgentModelType `json:"model_type"`
	// Agent portrait image URL.
	PortraitURL OptURI      `json:"portrait_url"`
	CreatedAt   OptDateTime `json:"created_at"`
	UpdatedAt   OptDateTime `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Agent) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Agent) GetName() OptString {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *Agent) GetStatus() AgentStatus {
	return s.Status
}

// GetPrompt returns the value of Prompt.
func (s *Agent) GetPrompt() OptString {
	return s.Prompt
}

// GetModelType returns the value of ModelType.
func (s *Agent) GetModelType() OptAgentModelType {
	return s.ModelType
}

// GetPortraitURL returns the value of PortraitURL.
func (s *Agent) GetPortraitURL() OptURI {
	return s.PortraitURL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Agent) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Agent) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Agent) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Agent) SetName(val OptString) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *Agent) SetStatus(val AgentStatus) {
	s.Status = val
}

// SetPrompt sets the value of Prompt.
func (s *Agent) SetPrompt(val OptString) {
	s.Prompt = val
}

// SetModelType sets the value of ModelType.
func (s *Agent) SetModelType(val OptAgentModelType) {
	s.ModelType = val
}

// SetPortraitURL sets the value of PortraitURL.
func (s *Agent) SetPortraitURL(val OptURI) {
	s.PortraitURL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Agent) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Agent) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Agent) createAgentRes() {}
func (*Agent) getAgentRes()    {}
func (*Agent) updateAgentRes() {}

// Ref: #/components/schemas/AgentList
type AgentList struct {
	Agents []Agent `json:"agents"`
	Total  OptInt  `json:"total"`
	Limit  OptInt  `json:"limit"`
	Offset OptInt  `json:"offset"`
}

// GetAgents returns the value of Agents.
func (s *AgentList) GetAgents() []Agent {
	return s.Agents
}

// GetTotal returns the value of Total.
func (s *AgentList) GetTotal() OptInt {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *AgentList) GetLimit() OptInt {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *AgentList) GetOffset() OptInt {
	return s.Offset
}

// SetAgents sets the value of Agents.
func (s *AgentList) SetAgents(val []Agent) {
	s.Agents = val
}

// SetTotal sets the value of Total.
func (s *AgentList) SetTotal(val OptInt) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *AgentList) SetLimit(val OptInt) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *AgentList) SetOffset(val OptInt) {
	s.Offset = val
}

func (*AgentList) listAgentsRes() {}

// Avatar model type.
type AgentModelType string

const (
	AgentModelTypeEssence    AgentModelType = "essence"
	AgentModelTypeExpression AgentModelType = "expression"
)

// AllValues returns all AgentModelType values.
func (AgentModelType) AllValues() []AgentModelType {
	return []AgentModelType{
		AgentModelTypeEssence,
		AgentModelTypeExpression,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AgentModelType) MarshalText() ([]byte, error) {
	switch s {
	case AgentModelTypeEssence:
		return []byte(s), nil
	case AgentModelTypeExpression:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AgentModelType) UnmarshalText(data []byte) error {
	switch AgentModelType(data) {
	case AgentModelTypeEssence:
		*s = AgentModelTypeEssence
		return nil
	case AgentModelTypeExpression:
		*s = AgentModelTypeExpression
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Agent generation status.
type AgentStatus string

const (
	AgentStatusPending    AgentStatus = "pending"
	AgentStatusProcessing AgentStatus = "processing"
	AgentStatusReady      AgentStatus = "ready"
	AgentStatusFailed     AgentStatus = "failed"
)

// AllValues returns all AgentStatus values.
func (AgentStatus) AllValues() []AgentStatus {
	return []AgentStatus{
		AgentStatusPending,
		AgentStatusProcessing,
		AgentStatusReady,
		AgentStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AgentStatus) MarshalText() ([]byte, error) {
	switch s {
	case AgentStatusPending:
		return []byte(s), nil
	case AgentStatusProcessing:
		return []byte(s), nil
	case AgentStatusReady:
		return []byte(s), nil
	case AgentStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AgentStatus) UnmarshalText(data []byte) error {
	switch AgentStatus(data) {
	case AgentStatusPending:
		*s = AgentStatusPending
		return nil
	case AgentStatusProcessing:
		*s = AgentStatusProcessing
		return nil
	case AgentStatusReady:
		*s = AgentStatusReady
		return nil
	case AgentStatusFailed:
		*s = AgentStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ApiSecret struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiSecret) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ApiSecret) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ApiSecret) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ApiSecret) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Balance
type Balance struct {
	// Available credits.
	Credits OptFloat64 `json:"credits"`
	// Estimated minutes by model type.
	MinutesEstimate OptBalanceMinutesEstimate `json:"minutes_estimate"`
}

// GetCredits returns the value of Credits.
func (s *Balance) GetCredits() OptFloat64 {
	return s.Credits
}

// GetMinutesEstimate returns the value of MinutesEstimate.
func (s *Balance) GetMinutesEstimate() OptBalanceMinutesEstimate {
	return s.MinutesEstimate
}

// SetCredits sets the value of Credits.
func (s *Balance) SetCredits(val OptFloat64) {
	s.Credits = val
}

// SetMinutesEstimate sets the value of MinutesEstimate.
func (s *Balance) SetMinutesEstimate(val OptBalanceMinutesEstimate) {
	s.MinutesEstimate = val
}

func (*Balance) getBalanceRes() {}

// Estimated minutes by model type.
type BalanceMinutesEstimate struct {
	Essence    OptFloat64 `json:"essence"`
	Expression OptFloat64 `json:"expression"`
}

// GetEssence returns the value of Essence.
func (s *BalanceMinutesEstimate) GetEssence() OptFloat64 {
	return s.Essence
}

// GetExpression returns the value of Expression.
func (s *BalanceMinutesEstimate) GetExpression() OptFloat64 {
	return s.Expression
}

// SetEssence sets the value of Essence.
func (s *BalanceMinutesEstimate) SetEssence(val OptFloat64) {
	s.Essence = val
}

// SetExpression sets the value of Expression.
func (s *BalanceMinutesEstimate) SetExpression(val OptFloat64) {
	s.Expression = val
}

type CreateAgentBadRequest Error

func (*CreateAgentBadRequest) createAgentRes() {}

// Ref: #/components/schemas/CreateAgentRequest
type CreateAgentRequest struct {
	// Agent display name.
	Name OptString `json:"name"`
	// Agent personality prompt.
	Prompt OptString `json:"prompt"`
	// Portrait image URL.
	PortraitURL OptURI `json:"portrait_url"`
	// Portrait image as base64.
	PortraitBase64 OptString `json:"portrait_base64"`
	// Avatar model type.
	ModelType OptCreateAgentRequestModelType `json:"model_type"`
}

// GetName returns the value of Name.
func (s *CreateAgentRequest) GetName() OptString {
	return s.Name
}

// GetPrompt returns the value of Prompt.
func (s *CreateAgentRequest) GetPrompt() OptString {
	return s.Prompt
}

// GetPortraitURL returns the value of PortraitURL.
func (s *CreateAgentRequest) GetPortraitURL() OptURI {
	return s.PortraitURL
}

// GetPortraitBase64 returns the value of PortraitBase64.
func (s *CreateAgentRequest) GetPortraitBase64() OptString {
	return s.PortraitBase64
}

// GetModelType returns the value of ModelType.
func (s *CreateAgentRequest) GetModelType() OptCreateAgentRequestModelType {
	return s.ModelType
}

// SetName sets the value of Name.
func (s *CreateAgentRequest) SetName(val OptString) {
	s.Name = val
}

// SetPrompt sets the value of Prompt.
func (s *CreateAgentRequest) SetPrompt(val OptString) {
	s.Prompt = val
}

// SetPortraitURL sets the value of PortraitURL.
func (s *CreateAgentRequest) SetPortraitURL(val OptURI) {
	s.PortraitURL = val
}

// SetPortraitBase64 sets the value of PortraitBase64.
func (s *CreateAgentRequest) SetPortraitBase64(val OptString) {
	s.PortraitBase64 = val
}

// SetModelType sets the value of ModelType.
func (s *CreateAgentRequest) SetModelType(val OptCreateAgentRequestModelType) {
	s.ModelType = val
}

// Avatar model type.
type CreateAgentRequestModelType string

const (
	CreateAgentRequestModelTypeEssence    CreateAgentRequestModelType = "essence"
	CreateAgentRequestModelTypeExpression CreateAgentRequestModelType = "expression"
)

// AllValues returns all CreateAgentRequestModelType values.
func (CreateAgentRequestModelType) AllValues() []CreateAgentRequestModelType {
	return []CreateAgentRequestModelType{
		CreateAgentRequestModelTypeEssence,
		CreateAgentRequestModelTypeExpression,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateAgentRequestModelType) MarshalText() ([]byte, error) {
	switch s {
	case CreateAgentRequestModelTypeEssence:
		return []byte(s), nil
	case CreateAgentRequestModelTypeExpression:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateAgentRequestModelType) UnmarshalText(data []byte) error {
	switch CreateAgentRequestModelType(data) {
	case CreateAgentRequestModelTypeEssence:
		*s = CreateAgentRequestModelTypeEssence
		return nil
	case CreateAgentRequestModelTypeExpression:
		*s = CreateAgentRequestModelTypeExpression
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateAgentUnauthorized Error

func (*CreateAgentUnauthorized) createAgentRes() {}

// Ref: #/components/schemas/CreateEmbedTokenRequest
type CreateEmbedTokenRequest struct {
	AgentID string `json:"agent_id"`
	// Token time-to-live.
	TTLSeconds OptInt `json:"ttl_seconds"`
}

// GetAgentID returns the value of AgentID.
func (s *CreateEmbedTokenRequest) GetAgentID() string {
	return s.AgentID
}

// GetTTLSeconds returns the value of TTLSeconds.
func (s *CreateEmbedTokenRequest) GetTTLSeconds() OptInt {
	return s.TTLSeconds
}

// SetAgentID sets the value of AgentID.
func (s *CreateEmbedTokenRequest) SetAgentID(val string) {
	s.AgentID = val
}

// SetTTLSeconds sets the value of TTLSeconds.
func (s *CreateEmbedTokenRequest) SetTTLSeconds(val OptInt) {
	s.TTLSeconds = val
}

type CreateSessionBadRequest Error

func (*CreateSessionBadRequest) createSessionRes() {}

// Ref: #/components/schemas/CreateSessionRequest
type CreateSessionRequest struct {
	// Agent to use for this session.
	AgentID string `json:"agent_id"`
	// Optional external LiveKit URL.
	LivekitURL OptString `json:"livekit_url"`
	// Optional external LiveKit token.
	LivekitToken OptString `json:"livekit_token"`
}

// GetAgentID returns the value of AgentID.
func (s *CreateSessionRequest) GetAgentID() string {
	return s.AgentID
}

// GetLivekitURL returns the value of LivekitURL.
func (s *CreateSessionRequest) GetLivekitURL() OptString {
	return s.LivekitURL
}

// GetLivekitToken returns the value of LivekitToken.
func (s *CreateSessionRequest) GetLivekitToken() OptString {
	return s.LivekitToken
}

// SetAgentID sets the value of AgentID.
func (s *CreateSessionRequest) SetAgentID(val string) {
	s.AgentID = val
}

// SetLivekitURL sets the value of LivekitURL.
func (s *CreateSessionRequest) SetLivekitURL(val OptString) {
	s.LivekitURL = val
}

// SetLivekitToken sets the value of LivekitToken.
func (s *CreateSessionRequest) SetLivekitToken(val OptString) {
	s.LivekitToken = val
}

type CreateSessionUnauthorized Error

func (*CreateSessionUnauthorized) createSessionRes() {}

type CreateVideoBadRequest Error

func (*CreateVideoBadRequest) createVideoRes() {}

// Ref: #/components/schemas/CreateVideoRequest
type CreateVideoRequest struct {
	// Agent ID.
	AgentID string `json:"agent_id"`
	// Script text (mutually exclusive with audio_url).
	Text OptString `json:"text"`
	// Audio URL (mutually exclusive with text).
	AudioURL OptURI `json:"audio_url"`
	// Voice ID for TTS (when using text).
	VoiceID OptString `json:"voice_id"`
}

// GetAgentID returns the value of AgentID.
func (s *CreateVideoRequest) GetAgentID() string {
	return s.AgentID
}

// GetText returns the value of Text.
func (s *CreateVideoRequest) GetText() OptString {
	return s.Text
}

// GetAudioURL returns the value of AudioURL.
func (s *CreateVideoRequest) GetAudioURL() OptURI {
	return s.AudioURL
}

// GetVoiceID returns the value of VoiceID.
func (s *CreateVideoRequest) GetVoiceID() OptString {
	return s.VoiceID
}

// SetAgentID sets the value of AgentID.
func (s *CreateVideoRequest) SetAgentID(val string) {
	s.AgentID = val
}

// SetText sets the value of Text.
func (s *CreateVideoRequest) SetText(val OptString) {
	s.Text = val
}

// SetAudioURL sets the value of AudioURL.
func (s *CreateVideoRequest) SetAudioURL(val OptURI) {
	s.AudioURL = val
}

// SetVoiceID sets the value of VoiceID.
func (s *CreateVideoRequest) SetVoiceID(val OptString) {
	s.VoiceID = val
}

type CreateVideoUnauthorized Error

func (*CreateVideoUnauthorized) createVideoRes() {}

type CreateWebhookBadRequest Error

func (*CreateWebhookBadRequest) createWebhookRes() {}

// Ref: #/components/schemas/CreateWebhookRequest
type CreateWebhookRequest struct {
	URL    url.URL                          `json:"url"`
	Events []CreateWebhookRequestEventsItem `json:"events"`
}

// GetURL returns the value of URL.
func (s *CreateWebhookRequest) GetURL() url.URL {
	return s.URL
}

// GetEvents returns the value of Events.
func (s *CreateWebhookRequest) GetEvents() []CreateWebhookRequestEventsItem {
	return s.Events
}

// SetURL sets the value of URL.
func (s *CreateWebhookRequest) SetURL(val url.URL) {
	s.URL = val
}

// SetEvents sets the value of Events.
func (s *CreateWebhookRequest) SetEvents(val []CreateWebhookRequestEventsItem) {
	s.Events = val
}

type CreateWebhookRequestEventsItem string

const (
	CreateWebhookRequestEventsItemAgentReady  CreateWebhookRequestEventsItem = "agent.ready"
	CreateWebhookRequestEventsItemAgentFailed CreateWebhookRequestEventsItem = "agent.failed"
)

// AllValues returns all CreateWebhookRequestEventsItem values.
func (CreateWebhookRequestEventsItem) AllValues() []CreateWebhookRequestEventsItem {
	return []CreateWebhookRequestEventsItem{
		CreateWebhookRequestEventsItemAgentReady,
		CreateWebhookRequestEventsItemAgentFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateWebhookRequestEventsItem) MarshalText() ([]byte, error) {
	switch s {
	case CreateWebhookRequestEventsItemAgentReady:
		return []byte(s), nil
	case CreateWebhookRequestEventsItemAgentFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateWebhookRequestEventsItem) UnmarshalText(data []byte) error {
	switch CreateWebhookRequestEventsItem(data) {
	case CreateWebhookRequestEventsItemAgentReady:
		*s = CreateWebhookRequestEventsItemAgentReady
		return nil
	case CreateWebhookRequestEventsItemAgentFailed:
		*s = CreateWebhookRequestEventsItemAgentFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateWebhookUnauthorized Error

func (*CreateWebhookUnauthorized) createWebhookRes() {}

// DeleteAgentNoContent is response for DeleteAgent operation.
type DeleteAgentNoContent struct{}

func (*DeleteAgentNoContent) deleteAgentRes() {}

type DeleteAgentNotFound Error

func (*DeleteAgentNotFound) deleteAgentRes() {}

type DeleteAgentUnauthorized Error

func (*DeleteAgentUnauthorized) deleteAgentRes() {}

// DeleteWebhookNoContent is response for DeleteWebhook operation.
type DeleteWebhookNoContent struct{}

func (*DeleteWebhookNoContent) deleteWebhookRes() {}

type DeleteWebhookNotFound Error

func (*DeleteWebhookNotFound) deleteWebhookRes() {}

type DeleteWebhookUnauthorized Error

func (*DeleteWebhookUnauthorized) deleteWebhookRes() {}

// Ref: #/components/schemas/EmbedToken
type EmbedToken struct {
	Token     OptString   `json:"token"`
	ExpiresAt OptDateTime `json:"expires_at"`
}

// GetToken returns the value of Token.
func (s *EmbedToken) GetToken() OptString {
	return s.Token
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *EmbedToken) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// SetToken sets the value of Token.
func (s *EmbedToken) SetToken(val OptString) {
	s.Token = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *EmbedToken) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

func (*EmbedToken) createEmbedTokenRes() {}

// EndSessionNoContent is response for EndSession operation.
type EndSessionNoContent struct{}

func (*EndSessionNoContent) endSessionRes() {}

type EndSessionNotFound Error

func (*EndSessionNotFound) endSessionRes() {}

type EndSessionUnauthorized Error

func (*EndSessionUnauthorized) endSessionRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// Error code.
	Error string `json:"error"`
	// Human-readable error message.
	Message string `json:"message"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) createEmbedTokenRes() {}
func (*Error) getBalanceRes()       {}
func (*Error) listAgentsRes()       {}
func (*Error) listVoicesRes()       {}
func (*Error) listWebhooksRes()     {}
func (*Error) validateRes()         {}

// Ref: #/components/schemas/File
type File struct {
	ID          OptString   `json:"id"`
	URL         OptURI      `json:"url"`
	ContentType OptString   `json:"content_type"`
	SizeBytes   OptInt      `json:"size_bytes"`
	CreatedAt   OptDateTime `json:"created_at"`
}

// GetID returns the value of ID.
func (s *File) GetID() OptString {
	return s.ID
}

// GetURL returns the value of URL.
func (s *File) GetURL() OptURI {
	return s.URL
}

// GetContentType returns the value of ContentType.
func (s *File) GetContentType() OptString {
	return s.ContentType
}

// GetSizeBytes returns the value of SizeBytes.
func (s *File) GetSizeBytes() OptInt {
	return s.SizeBytes
}

// GetCreatedAt returns the value of CreatedAt.
func (s *File) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *File) SetID(val OptString) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *File) SetURL(val OptURI) {
	s.URL = val
}

// SetContentType sets the value of ContentType.
func (s *File) SetContentType(val OptString) {
	s.ContentType = val
}

// SetSizeBytes sets the value of SizeBytes.
func (s *File) SetSizeBytes(val OptInt) {
	s.SizeBytes = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *File) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*File) uploadFileRes() {}

type GetAgentNotFound Error

func (*GetAgentNotFound) getAgentRes() {}

type GetAgentUnauthorized Error

func (*GetAgentUnauthorized) getAgentRes() {}

type GetSessionNotFound Error

func (*GetSessionNotFound) getSessionRes() {}

type GetSessionUnauthorized Error

func (*GetSessionUnauthorized) getSessionRes() {}

type GetVideoNotFound Error

func (*GetVideoNotFound) getVideoRes() {}

type GetVideoUnauthorized Error

func (*GetVideoUnauthorized) getVideoRes() {}

// NewOptAgentModelType returns new OptAgentModelType with value set to v.
func NewOptAgentModelType(v AgentModelType) OptAgentModelType {
	return OptAgentModelType{
		Value: v,
		Set:   true,
	}
}

// OptAgentModelType is optional AgentModelType.
type OptAgentModelType struct {
	Value AgentModelType
	Set   bool
}

// IsSet returns true if OptAgentModelType was set.
func (o OptAgentModelType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAgentModelType) Reset() {
	var v AgentModelType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAgentModelType) SetTo(v AgentModelType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAgentModelType) Get() (v AgentModelType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAgentModelType) Or(d AgentModelType) AgentModelType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBalanceMinutesEstimate returns new OptBalanceMinutesEstimate with value set to v.
func NewOptBalanceMinutesEstimate(v BalanceMinutesEstimate) OptBalanceMinutesEstimate {
	return OptBalanceMinutesEstimate{
		Value: v,
		Set:   true,
	}
}

// OptBalanceMinutesEstimate is optional BalanceMinutesEstimate.
type OptBalanceMinutesEstimate struct {
	Value BalanceMinutesEstimate
	Set   bool
}

// IsSet returns true if OptBalanceMinutesEstimate was set.
func (o OptBalanceMinutesEstimate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBalanceMinutesEstimate) Reset() {
	var v BalanceMinutesEstimate
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBalanceMinutesEstimate) SetTo(v BalanceMinutesEstimate) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBalanceMinutesEstimate) Get() (v BalanceMinutesEstimate, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBalanceMinutesEstimate) Or(d BalanceMinutesEstimate) BalanceMinutesEstimate {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateAgentRequestModelType returns new OptCreateAgentRequestModelType with value set to v.
func NewOptCreateAgentRequestModelType(v CreateAgentRequestModelType) OptCreateAgentRequestModelType {
	return OptCreateAgentRequestModelType{
		Value: v,
		Set:   true,
	}
}

// OptCreateAgentRequestModelType is optional CreateAgentRequestModelType.
type OptCreateAgentRequestModelType struct {
	Value CreateAgentRequestModelType
	Set   bool
}

// IsSet returns true if OptCreateAgentRequestModelType was set.
func (o OptCreateAgentRequestModelType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateAgentRequestModelType) Reset() {
	var v CreateAgentRequestModelType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateAgentRequestModelType) SetTo(v CreateAgentRequestModelType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateAgentRequestModelType) Get() (v CreateAgentRequestModelType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateAgentRequestModelType) Or(d CreateAgentRequestModelType) CreateAgentRequestModelType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptVoiceGender returns new OptVoiceGender with value set to v.
func NewOptVoiceGender(v VoiceGender) OptVoiceGender {
	return OptVoiceGender{
		Value: v,
		Set:   true,
	}
}

// OptVoiceGender is optional VoiceGender.
type OptVoiceGender struct {
	Value VoiceGender
	Set   bool
}

// IsSet returns true if OptVoiceGender was set.
func (o OptVoiceGender) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptVoiceGender) Reset() {
	var v VoiceGender
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptVoiceGender) SetTo(v VoiceGender) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptVoiceGender) Get() (v VoiceGender, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptVoiceGender) Or(d VoiceGender) VoiceGender {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Session
type Session struct {
	// Session ID.
	ID string `json:"id"`
	// Agent ID.
	AgentID string        `json:"agent_id"`
	Status  SessionStatus `json:"status"`
	// LiveKit WebSocket URL.
	LivekitURL OptString `json:"livekit_url"`
	// LiveKit JWT token.
	LivekitToken OptString   `json:"livekit_token"`
	CreatedAt    OptDateTime `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Session) GetID() string {
	return s.ID
}

// GetAgentID returns the value of AgentID.
func (s *Session) GetAgentID() string {
	return s.AgentID
}

// GetStatus returns the value of Status.
func (s *Session) GetStatus() SessionStatus {
	return s.Status
}

// GetLivekitURL returns the value of LivekitURL.
func (s *Session) GetLivekitURL() OptString {
	return s.LivekitURL
}

// GetLivekitToken returns the value of LivekitToken.
func (s *Session) GetLivekitToken() OptString {
	return s.LivekitToken
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Session) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Session) SetID(val string) {
	s.ID = val
}

// SetAgentID sets the value of AgentID.
func (s *Session) SetAgentID(val string) {
	s.AgentID = val
}

// SetStatus sets the value of Status.
func (s *Session) SetStatus(val SessionStatus) {
	s.Status = val
}

// SetLivekitURL sets the value of LivekitURL.
func (s *Session) SetLivekitURL(val OptString) {
	s.LivekitURL = val
}

// SetLivekitToken sets the value of LivekitToken.
func (s *Session) SetLivekitToken(val OptString) {
	s.LivekitToken = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Session) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*Session) createSessionRes() {}
func (*Session) getSessionRes()    {}

type SessionStatus string

const (
	SessionStatusActive SessionStatus = "active"
	SessionStatusEnded  SessionStatus = "ended"
)

// AllValues returns all SessionStatus values.
func (SessionStatus) AllValues() []SessionStatus {
	return []SessionStatus{
		SessionStatusActive,
		SessionStatusEnded,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SessionStatus) MarshalText() ([]byte, error) {
	switch s {
	case SessionStatusActive:
		return []byte(s), nil
	case SessionStatusEnded:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SessionStatus) UnmarshalText(data []byte) error {
	switch SessionStatus(data) {
	case SessionStatusActive:
		*s = SessionStatusActive
		return nil
	case SessionStatusEnded:
		*s = SessionStatusEnded
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SpeakNotFound Error

func (*SpeakNotFound) speakRes() {}

// Ref: #/components/schemas/SpeakRequest
type SpeakRequest struct {
	// Text for the agent to speak.
	Text string `json:"text"`
	// Voice to use (optional).
	VoiceID OptString `json:"voice_id"`
}

// GetText returns the value of Text.
func (s *SpeakRequest) GetText() string {
	return s.Text
}

// GetVoiceID returns the value of VoiceID.
func (s *SpeakRequest) GetVoiceID() OptString {
	return s.VoiceID
}

// SetText sets the value of Text.
func (s *SpeakRequest) SetText(val string) {
	s.Text = val
}

// SetVoiceID sets the value of VoiceID.
func (s *SpeakRequest) SetVoiceID(val OptString) {
	s.VoiceID = val
}

// Ref: #/components/schemas/SpeakResponse
type SpeakResponse struct {
	Success OptBool `json:"success"`
	// Estimated speech duration.
	DurationMs OptInt `json:"duration_ms"`
}

// GetSuccess returns the value of Success.
func (s *SpeakResponse) GetSuccess() OptBool {
	return s.Success
}

// GetDurationMs returns the value of DurationMs.
func (s *SpeakResponse) GetDurationMs() OptInt {
	return s.DurationMs
}

// SetSuccess sets the value of Success.
func (s *SpeakResponse) SetSuccess(val OptBool) {
	s.Success = val
}

// SetDurationMs sets the value of DurationMs.
func (s *SpeakResponse) SetDurationMs(val OptInt) {
	s.DurationMs = val
}

func (*SpeakResponse) speakRes() {}

type SpeakUnauthorized Error

func (*SpeakUnauthorized) speakRes() {}

// Ref: #/components/schemas/TTSRequest
type TTSRequest struct {
	// Text to synthesize.
	Text string `json:"text"`
	// Voice ID (M1-M5, F1-F5).
	VoiceID OptString `json:"voice_id"`
	// Language code (e.g., en, es, fr).
	Language OptString `json:"language"`
}

// GetText returns the value of Text.
func (s *TTSRequest) GetText() string {
	return s.Text
}

// GetVoiceID returns the value of VoiceID.
func (s *TTSRequest) GetVoiceID() OptString {
	return s.VoiceID
}

// GetLanguage returns the value of Language.
func (s *TTSRequest) GetLanguage() OptString {
	return s.Language
}

// SetText sets the value of Text.
func (s *TTSRequest) SetText(val string) {
	s.Text = val
}

// SetVoiceID sets the value of VoiceID.
func (s *TTSRequest) SetVoiceID(val OptString) {
	s.VoiceID = val
}

// SetLanguage sets the value of Language.
func (s *TTSRequest) SetLanguage(val OptString) {
	s.Language = val
}

type TextToSpeechBadRequest Error

func (*TextToSpeechBadRequest) textToSpeechRes() {}

type TextToSpeechOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TextToSpeechOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TextToSpeechOK) textToSpeechRes() {}

type TextToSpeechUnauthorized Error

func (*TextToSpeechUnauthorized) textToSpeechRes() {}

type UpdateAgentNotFound Error

func (*UpdateAgentNotFound) updateAgentRes() {}

// Ref: #/components/schemas/UpdateAgentRequest
type UpdateAgentRequest struct {
	Name   OptString `json:"name"`
	Prompt OptString `json:"prompt"`
}

// GetName returns the value of Name.
func (s *UpdateAgentRequest) GetName() OptString {
	return s.Name
}

// GetPrompt returns the value of Prompt.
func (s *UpdateAgentRequest) GetPrompt() OptString {
	return s.Prompt
}

// SetName sets the value of Name.
func (s *UpdateAgentRequest) SetName(val OptString) {
	s.Name = val
}

// SetPrompt sets the value of Prompt.
func (s *UpdateAgentRequest) SetPrompt(val OptString) {
	s.Prompt = val
}

type UpdateAgentUnauthorized Error

func (*UpdateAgentUnauthorized) updateAgentRes() {}

type UploadFileBadRequest Error

func (*UploadFileBadRequest) uploadFileRes() {}

// Ref: #/components/schemas/UploadFileRequest
type UploadFileRequest struct {
	// URL to download file from.
	URL OptURI `json:"url"`
	// File content as base64.
	Base64 OptString `json:"base64"`
	// Original filename.
	Filename OptString `json:"filename"`
	// MIME type.
	ContentType OptString `json:"content_type"`
}

// GetURL returns the value of URL.
func (s *UploadFileRequest) GetURL() OptURI {
	return s.URL
}

// GetBase64 returns the value of Base64.
func (s *UploadFileRequest) GetBase64() OptString {
	return s.Base64
}

// GetFilename returns the value of Filename.
func (s *UploadFileRequest) GetFilename() OptString {
	return s.Filename
}

// GetContentType returns the value of ContentType.
func (s *UploadFileRequest) GetContentType() OptString {
	return s.ContentType
}

// SetURL sets the value of URL.
func (s *UploadFileRequest) SetURL(val OptURI) {
	s.URL = val
}

// SetBase64 sets the value of Base64.
func (s *UploadFileRequest) SetBase64(val OptString) {
	s.Base64 = val
}

// SetFilename sets the value of Filename.
func (s *UploadFileRequest) SetFilename(val OptString) {
	s.Filename = val
}

// SetContentType sets the value of ContentType.
func (s *UploadFileRequest) SetContentType(val OptString) {
	s.ContentType = val
}

type UploadFileUnauthorized Error

func (*UploadFileUnauthorized) uploadFileRes() {}

// Ref: #/components/schemas/ValidateResponse
type ValidateResponse struct {
	Valid     OptBool   `json:"valid"`
	AccountID OptString `json:"account_id"`
}

// GetValid returns the value of Valid.
func (s *ValidateResponse) GetValid() OptBool {
	return s.Valid
}

// GetAccountID returns the value of AccountID.
func (s *ValidateResponse) GetAccountID() OptString {
	return s.AccountID
}

// SetValid sets the value of Valid.
func (s *ValidateResponse) SetValid(val OptBool) {
	s.Valid = val
}

// SetAccountID sets the value of AccountID.
func (s *ValidateResponse) SetAccountID(val OptString) {
	s.AccountID = val
}

func (*ValidateResponse) validateRes() {}

// Ref: #/components/schemas/VideoJob
type VideoJob struct {
	ID      string         `json:"id"`
	AgentID OptString      `json:"agent_id"`
	Status  VideoJobStatus `json:"status"`
	// Download URL (when completed).
	VideoURL        OptURI     `json:"video_url"`
	DurationSeconds OptFloat64 `json:"duration_seconds"`
	// Error message (when failed).
	Error     OptString   `json:"error"`
	CreatedAt OptDateTime `json:"created_at"`
}

// GetID returns the value of ID.
func (s *VideoJob) GetID() string {
	return s.ID
}

// GetAgentID returns the value of AgentID.
func (s *VideoJob) GetAgentID() OptString {
	return s.AgentID
}

// GetStatus returns the value of Status.
func (s *VideoJob) GetStatus() VideoJobStatus {
	return s.Status
}

// GetVideoURL returns the value of VideoURL.
func (s *VideoJob) GetVideoURL() OptURI {
	return s.VideoURL
}

// GetDurationSeconds returns the value of DurationSeconds.
func (s *VideoJob) GetDurationSeconds() OptFloat64 {
	return s.DurationSeconds
}

// GetError returns the value of Error.
func (s *VideoJob) GetError() OptString {
	return s.Error
}

// GetCreatedAt returns the value of CreatedAt.
func (s *VideoJob) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *VideoJob) SetID(val string) {
	s.ID = val
}

// SetAgentID sets the value of AgentID.
func (s *VideoJob) SetAgentID(val OptString) {
	s.AgentID = val
}

// SetStatus sets the value of Status.
func (s *VideoJob) SetStatus(val VideoJobStatus) {
	s.Status = val
}

// SetVideoURL sets the value of VideoURL.
func (s *VideoJob) SetVideoURL(val OptURI) {
	s.VideoURL = val
}

// SetDurationSeconds sets the value of DurationSeconds.
func (s *VideoJob) SetDurationSeconds(val OptFloat64) {
	s.DurationSeconds = val
}

// SetError sets the value of Error.
func (s *VideoJob) SetError(val OptString) {
	s.Error = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *VideoJob) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*VideoJob) createVideoRes() {}
func (*VideoJob) getVideoRes()    {}

type VideoJobStatus string

const (
	VideoJobStatusPending    VideoJobStatus = "pending"
	VideoJobStatusProcessing VideoJobStatus = "processing"
	VideoJobStatusCompleted  VideoJobStatus = "completed"
	VideoJobStatusFailed     VideoJobStatus = "failed"
)

// AllValues returns all VideoJobStatus values.
func (VideoJobStatus) AllValues() []VideoJobStatus {
	return []VideoJobStatus{
		VideoJobStatusPending,
		VideoJobStatusProcessing,
		VideoJobStatusCompleted,
		VideoJobStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s VideoJobStatus) MarshalText() ([]byte, error) {
	switch s {
	case VideoJobStatusPending:
		return []byte(s), nil
	case VideoJobStatusProcessing:
		return []byte(s), nil
	case VideoJobStatusCompleted:
		return []byte(s), nil
	case VideoJobStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *VideoJobStatus) UnmarshalText(data []byte) error {
	switch VideoJobStatus(data) {
	case VideoJobStatusPending:
		*s = VideoJobStatusPending
		return nil
	case VideoJobStatusProcessing:
		*s = VideoJobStatusProcessing
		return nil
	case VideoJobStatusCompleted:
		*s = VideoJobStatusCompleted
		return nil
	case VideoJobStatusFailed:
		*s = VideoJobStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Voice
type Voice struct {
	ID         OptString      `json:"id"`
	Name       OptString      `json:"name"`
	Gender     OptVoiceGender `json:"gender"`
	Language   OptString      `json:"language"`
	PreviewURL OptURI         `json:"preview_url"`
}

// GetID returns the value of ID.
func (s *Voice) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *Voice) GetName() OptString {
	return s.Name
}

// GetGender returns the value of Gender.
func (s *Voice) GetGender() OptVoiceGender {
	return s.Gender
}

// GetLanguage returns the value of Language.
func (s *Voice) GetLanguage() OptString {
	return s.Language
}

// GetPreviewURL returns the value of PreviewURL.
func (s *Voice) GetPreviewURL() OptURI {
	return s.PreviewURL
}

// SetID sets the value of ID.
func (s *Voice) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Voice) SetName(val OptString) {
	s.Name = val
}

// SetGender sets the value of Gender.
func (s *Voice) SetGender(val OptVoiceGender) {
	s.Gender = val
}

// SetLanguage sets the value of Language.
func (s *Voice) SetLanguage(val OptString) {
	s.Language = val
}

// SetPreviewURL sets the value of PreviewURL.
func (s *Voice) SetPreviewURL(val OptURI) {
	s.PreviewURL = val
}

type VoiceGender string

const (
	VoiceGenderMale   VoiceGender = "male"
	VoiceGenderFemale VoiceGender = "female"
)

// AllValues returns all VoiceGender values.
func (VoiceGender) AllValues() []VoiceGender {
	return []VoiceGender{
		VoiceGenderMale,
		VoiceGenderFemale,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s VoiceGender) MarshalText() ([]byte, error) {
	switch s {
	case VoiceGenderMale:
		return []byte(s), nil
	case VoiceGenderFemale:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *VoiceGender) UnmarshalText(data []byte) error {
	switch VoiceGender(data) {
	case VoiceGenderMale:
		*s = VoiceGenderMale
		return nil
	case VoiceGenderFemale:
		*s = VoiceGenderFemale
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/VoiceList
type VoiceList struct {
	Voices []Voice `json:"voices"`
}

// GetVoices returns the value of Voices.
func (s *VoiceList) GetVoices() []Voice {
	return s.Voices
}

// SetVoices sets the value of Voices.
func (s *VoiceList) SetVoices(val []Voice) {
	s.Voices = val
}

func (*VoiceList) listVoicesRes() {}

// Ref: #/components/schemas/Webhook
type Webhook struct {
	ID     OptString           `json:"id"`
	URL    OptURI              `json:"url"`
	Events []WebhookEventsItem `json:"events"`
	// Signing secret.
	Secret    OptString   `json:"secret"`
	CreatedAt OptDateTime `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Webhook) GetID() OptString {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Webhook) GetURL() OptURI {
	return s.URL
}

// GetEvents returns the value of Events.
func (s *Webhook) GetEvents() []WebhookEventsItem {
	return s.Events
}

// GetSecret returns the value of Secret.
func (s *Webhook) GetSecret() OptString {
	return s.Secret
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Webhook) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Webhook) SetID(val OptString) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Webhook) SetURL(val OptURI) {
	s.URL = val
}

// SetEvents sets the value of Events.
func (s *Webhook) SetEvents(val []WebhookEventsItem) {
	s.Events = val
}

// SetSecret sets the value of Secret.
func (s *Webhook) SetSecret(val OptString) {
	s.Secret = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Webhook) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*Webhook) createWebhookRes() {}

type WebhookEventsItem string

const (
	WebhookEventsItemAgentReady  WebhookEventsItem = "agent.ready"
	WebhookEventsItemAgentFailed WebhookEventsItem = "agent.failed"
)

// AllValues returns all WebhookEventsItem values.
func (WebhookEventsItem) AllValues() []WebhookEventsItem {
	return []WebhookEventsItem{
		WebhookEventsItemAgentReady,
		WebhookEventsItemAgentFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WebhookEventsItem) MarshalText() ([]byte, error) {
	switch s {
	case WebhookEventsItemAgentReady:
		return []byte(s), nil
	case WebhookEventsItemAgentFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WebhookEventsItem) UnmarshalText(data []byte) error {
	switch WebhookEventsItem(data) {
	case WebhookEventsItemAgentReady:
		*s = WebhookEventsItemAgentReady
		return nil
	case WebhookEventsItemAgentFailed:
		*s = WebhookEventsItemAgentFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/WebhookList
type WebhookList struct {
	Webhooks []Webhook `json:"webhooks"`
}

// GetWebhooks returns the value of Webhooks.
func (s *WebhookList) GetWebhooks() []Webhook {
	return s.Webhooks
}

// SetWebhooks sets the value of Webhooks.
func (s *WebhookList) SetWebhooks(val []Webhook) {
	s.Webhooks = val
}

func (*WebhookList) listWebhooksRes() {}
