// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateAgent implements createAgent operation.
	//
	// Generate a new avatar agent from a text prompt with optional image/audio.
	// Returns immediately with agent ID; use GET /v1/agents/{id} to poll status.
	//
	// POST /v1/agents
	CreateAgent(ctx context.Context, req *CreateAgentRequest) (CreateAgentRes, error)
	// CreateEmbedToken implements createEmbedToken operation.
	//
	// Mint a short-lived JWT for embedding avatar in websites.
	//
	// POST /v1/embed/token
	CreateEmbedToken(ctx context.Context, req *CreateEmbedTokenRequest) (CreateEmbedTokenRes, error)
	// CreateSession implements createSession operation.
	//
	// Create a new real-time conversation session with an agent.
	// Returns connection details for WebRTC/LiveKit.
	//
	// POST /v1/sessions
	CreateSession(ctx context.Context, req *CreateSessionRequest) (CreateSessionRes, error)
	// CreateVideo implements createVideo operation.
	//
	// Generate an MP4 talking video from text or audio.
	// This is an async operation; poll GET /v1/videos/{id} for status.
	//
	// POST /v1/videos
	CreateVideo(ctx context.Context, req *CreateVideoRequest) (CreateVideoRes, error)
	// CreateWebhook implements createWebhook operation.
	//
	// Create webhook.
	//
	// POST /v1/webhooks
	CreateWebhook(ctx context.Context, req *CreateWebhookRequest) (CreateWebhookRes, error)
	// DeleteAgent implements deleteAgent operation.
	//
	// Delete agent.
	//
	// DELETE /v1/agents/{agentId}
	DeleteAgent(ctx context.Context, params DeleteAgentParams) (DeleteAgentRes, error)
	// DeleteWebhook implements deleteWebhook operation.
	//
	// Delete webhook.
	//
	// DELETE /v1/webhooks/{webhookId}
	DeleteWebhook(ctx context.Context, params DeleteWebhookParams) (DeleteWebhookRes, error)
	// EndSession implements endSession operation.
	//
	// End a session.
	//
	// DELETE /v1/sessions/{sessionId}
	EndSession(ctx context.Context, params EndSessionParams) (EndSessionRes, error)
	// GetAgent implements getAgent operation.
	//
	// Get agent details.
	//
	// GET /v1/agents/{agentId}
	GetAgent(ctx context.Context, params GetAgentParams) (GetAgentRes, error)
	// GetBalance implements getBalance operation.
	//
	// Get account balance.
	//
	// GET /v1/billing/balance
	GetBalance(ctx context.Context) (GetBalanceRes, error)
	// GetSession implements getSession operation.
	//
	// Get session details.
	//
	// GET /v1/sessions/{sessionId}
	GetSession(ctx context.Context, params GetSessionParams) (GetSessionRes, error)
	// GetVideo implements getVideo operation.
	//
	// Get video job status.
	//
	// GET /v1/videos/{videoId}
	GetVideo(ctx context.Context, params GetVideoParams) (GetVideoRes, error)
	// ListAgents implements listAgents operation.
	//
	// List all agents.
	//
	// GET /v1/agents
	ListAgents(ctx context.Context, params ListAgentsParams) (ListAgentsRes, error)
	// ListVoices implements listVoices operation.
	//
	// List available voices.
	//
	// GET /v1/voices
	ListVoices(ctx context.Context) (ListVoicesRes, error)
	// ListWebhooks implements listWebhooks operation.
	//
	// List webhooks.
	//
	// GET /v1/webhooks
	ListWebhooks(ctx context.Context) (ListWebhooksRes, error)
	// Speak implements speak operation.
	//
	// Send text for the agent to speak with lip-sync.
	//
	// POST /v1/agents/{agentId}/speak
	Speak(ctx context.Context, req *SpeakRequest, params SpeakParams) (SpeakRes, error)
	// TextToSpeech implements textToSpeech operation.
	//
	// Convert text to audio using bitHuman TTS.
	//
	// POST /v1/tts
	TextToSpeech(ctx context.Context, req *TTSRequest) (TextToSpeechRes, error)
	// UpdateAgent implements updateAgent operation.
	//
	// Update agent.
	//
	// PATCH /v1/agents/{agentId}
	UpdateAgent(ctx context.Context, req *UpdateAgentRequest, params UpdateAgentParams) (UpdateAgentRes, error)
	// UploadFile implements uploadFile operation.
	//
	// Upload images, video, audio, or documents.
	//
	// POST /v1/files
	UploadFile(ctx context.Context, req *UploadFileRequest) (UploadFileRes, error)
	// Validate implements validate operation.
	//
	// Cheapest way to verify API key is valid.
	//
	// POST /v1/validate
	Validate(ctx context.Context) (ValidateRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
