// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteAgentParams is parameters of deleteAgent operation.
type DeleteAgentParams struct {
	// Agent ID.
	AgentId string
}

func unpackDeleteAgentParams(packed middleware.Parameters) (params DeleteAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "agentId",
			In:   "path",
		}
		params.AgentId = packed[key].(string)
	}
	return params
}

func decodeDeleteAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAgentParams, _ error) {
	// Decode path: agentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "agentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AgentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "agentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteWebhookParams is parameters of deleteWebhook operation.
type DeleteWebhookParams struct {
	// Webhook ID.
	WebhookId string
}

func unpackDeleteWebhookParams(packed middleware.Parameters) (params DeleteWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "webhookId",
			In:   "path",
		}
		params.WebhookId = packed[key].(string)
	}
	return params
}

func decodeDeleteWebhookParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteWebhookParams, _ error) {
	// Decode path: webhookId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "webhookId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.WebhookId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "webhookId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// EndSessionParams is parameters of endSession operation.
type EndSessionParams struct {
	// Session ID.
	SessionId string
}

func unpackEndSessionParams(packed middleware.Parameters) (params EndSessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(string)
	}
	return params
}

func decodeEndSessionParams(args [1]string, argsEscaped bool, r *http.Request) (params EndSessionParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAgentParams is parameters of getAgent operation.
type GetAgentParams struct {
	// Agent ID.
	AgentId string
}

func unpackGetAgentParams(packed middleware.Parameters) (params GetAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "agentId",
			In:   "path",
		}
		params.AgentId = packed[key].(string)
	}
	return params
}

func decodeGetAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAgentParams, _ error) {
	// Decode path: agentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "agentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AgentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "agentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSessionParams is parameters of getSession operation.
type GetSessionParams struct {
	// Session ID.
	SessionId string
}

func unpackGetSessionParams(packed middleware.Parameters) (params GetSessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(string)
	}
	return params
}

func decodeGetSessionParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSessionParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetVideoParams is parameters of getVideo operation.
type GetVideoParams struct {
	// Video job ID.
	VideoId string
}

func unpackGetVideoParams(packed middleware.Parameters) (params GetVideoParams) {
	{
		key := middleware.ParameterKey{
			Name: "videoId",
			In:   "path",
		}
		params.VideoId = packed[key].(string)
	}
	return params
}

func decodeGetVideoParams(args [1]string, argsEscaped bool, r *http.Request) (params GetVideoParams, _ error) {
	// Decode path: videoId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "videoId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.VideoId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "videoId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAgentsParams is parameters of listAgents operation.
type ListAgentsParams struct {
	// Maximum number of items to return.
	Limit OptInt `json:",omitempty,omitzero"`
	// Number of items to skip.
	Offset OptInt `json:",omitempty,omitzero"`
}

func unpackListAgentsParams(packed middleware.Parameters) (params ListAgentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	return params
}

func decodeListAgentsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListAgentsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: limit.
	{
		val := int(20)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        false,
							Min:           0,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SpeakParams is parameters of speak operation.
type SpeakParams struct {
	// Agent ID.
	AgentId string
}

func unpackSpeakParams(packed middleware.Parameters) (params SpeakParams) {
	{
		key := middleware.ParameterKey{
			Name: "agentId",
			In:   "path",
		}
		params.AgentId = packed[key].(string)
	}
	return params
}

func decodeSpeakParams(args [1]string, argsEscaped bool, r *http.Request) (params SpeakParams, _ error) {
	// Decode path: agentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "agentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AgentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "agentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateAgentParams is parameters of updateAgent operation.
type UpdateAgentParams struct {
	// Agent ID.
	AgentId string
}

func unpackUpdateAgentParams(packed middleware.Parameters) (params UpdateAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "agentId",
			In:   "path",
		}
		params.AgentId = packed[key].(string)
	}
	return params
}

func decodeUpdateAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateAgentParams, _ error) {
	// Decode path: agentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "agentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AgentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "agentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
