// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn1AllowedHeaders = map[string]string{
		"GET":  "Api-Secret",
		"POST": "Api-Secret,Content-Type",
	}
	rn8AllowedHeaders = map[string]string{
		"DELETE": "Api-Secret",
		"GET":    "Api-Secret",
		"PATCH":  "Api-Secret,Content-Type",
	}
	rn18AllowedHeaders = map[string]string{
		"POST": "Api-Secret,Content-Type",
	}
	rn13AllowedHeaders = map[string]string{
		"GET": "Api-Secret",
	}
	rn3AllowedHeaders = map[string]string{
		"POST": "Api-Secret,Content-Type",
	}
	rn20AllowedHeaders = map[string]string{
		"POST": "Api-Secret,Content-Type",
	}
	rn4AllowedHeaders = map[string]string{
		"POST": "Api-Secret,Content-Type",
	}
	rn12AllowedHeaders = map[string]string{
		"DELETE": "Api-Secret",
		"GET":    "Api-Secret",
	}
	rn19AllowedHeaders = map[string]string{
		"POST": "Api-Secret,Content-Type",
	}
	rn21AllowedHeaders = map[string]string{
		"POST": "Api-Secret",
	}
	rn5AllowedHeaders = map[string]string{
		"POST": "Api-Secret,Content-Type",
	}
	rn15AllowedHeaders = map[string]string{
		"GET": "Api-Secret",
	}
	rn17AllowedHeaders = map[string]string{
		"GET": "Api-Secret",
	}
	rn6AllowedHeaders = map[string]string{
		"GET":  "Api-Secret",
		"POST": "Api-Secret,Content-Type",
	}
	rn10AllowedHeaders = map[string]string{
		"DELETE": "Api-Secret",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"

			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "agents"

				if l := len("agents"); len(elem) >= l && elem[0:l] == "agents" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListAgentsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateAgentRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn1AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "agentId"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteAgentRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetAgentRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateAgentRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PATCH",
								allowedHeaders: rn8AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/speak"

						if l := len("/speak"); len(elem) >= l && elem[0:l] == "/speak" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleSpeakRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn18AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'b': // Prefix: "billing/balance"

				if l := len("billing/balance"); len(elem) >= l && elem[0:l] == "billing/balance" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetBalanceRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: rn13AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'e': // Prefix: "embed/token"

				if l := len("embed/token"); len(elem) >= l && elem[0:l] == "embed/token" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleCreateEmbedTokenRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn3AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'f': // Prefix: "files"

				if l := len("files"); len(elem) >= l && elem[0:l] == "files" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleUploadFileRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn20AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}

			case 's': // Prefix: "sessions"

				if l := len("sessions"); len(elem) >= l && elem[0:l] == "sessions" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "POST":
						s.handleCreateSessionRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn4AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "sessionId"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleEndSessionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetSessionRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET",
								allowedHeaders: rn12AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 't': // Prefix: "tts"

				if l := len("tts"); len(elem) >= l && elem[0:l] == "tts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleTextToSpeechRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn19AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'v': // Prefix: "v"

				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "alidate"

					if l := len("alidate"); len(elem) >= l && elem[0:l] == "alidate" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleValidateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn21AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'i': // Prefix: "ideos"

					if l := len("ideos"); len(elem) >= l && elem[0:l] == "ideos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "POST":
							s.handleCreateVideoRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn5AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "videoId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetVideoRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn15AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'o': // Prefix: "oices"

					if l := len("oices"); len(elem) >= l && elem[0:l] == "oices" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListVoicesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn17AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'w': // Prefix: "webhooks"

				if l := len("webhooks"); len(elem) >= l && elem[0:l] == "webhooks" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListWebhooksRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateWebhookRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn6AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "webhookId"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteWebhookRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE",
								allowedHeaders: rn10AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"

			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "agents"

				if l := len("agents"); len(elem) >= l && elem[0:l] == "agents" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListAgentsOperation
						r.summary = "List all agents"
						r.operationID = "listAgents"
						r.operationGroup = ""
						r.pathPattern = "/v1/agents"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateAgentOperation
						r.summary = "Generate a new avatar agent"
						r.operationID = "createAgent"
						r.operationGroup = ""
						r.pathPattern = "/v1/agents"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "agentId"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteAgentOperation
							r.summary = "Delete agent"
							r.operationID = "deleteAgent"
							r.operationGroup = ""
							r.pathPattern = "/v1/agents/{agentId}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetAgentOperation
							r.summary = "Get agent details"
							r.operationID = "getAgent"
							r.operationGroup = ""
							r.pathPattern = "/v1/agents/{agentId}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateAgentOperation
							r.summary = "Update agent"
							r.operationID = "updateAgent"
							r.operationGroup = ""
							r.pathPattern = "/v1/agents/{agentId}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/speak"

						if l := len("/speak"); len(elem) >= l && elem[0:l] == "/speak" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = SpeakOperation
								r.summary = "Make agent speak"
								r.operationID = "speak"
								r.operationGroup = ""
								r.pathPattern = "/v1/agents/{agentId}/speak"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'b': // Prefix: "billing/balance"

				if l := len("billing/balance"); len(elem) >= l && elem[0:l] == "billing/balance" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetBalanceOperation
						r.summary = "Get account balance"
						r.operationID = "getBalance"
						r.operationGroup = ""
						r.pathPattern = "/v1/billing/balance"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'e': // Prefix: "embed/token"

				if l := len("embed/token"); len(elem) >= l && elem[0:l] == "embed/token" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = CreateEmbedTokenOperation
						r.summary = "Create embed token"
						r.operationID = "createEmbedToken"
						r.operationGroup = ""
						r.pathPattern = "/v1/embed/token"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'f': // Prefix: "files"

				if l := len("files"); len(elem) >= l && elem[0:l] == "files" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = UploadFileOperation
						r.summary = "Upload a file"
						r.operationID = "uploadFile"
						r.operationGroup = ""
						r.pathPattern = "/v1/files"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 's': // Prefix: "sessions"

				if l := len("sessions"); len(elem) >= l && elem[0:l] == "sessions" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						r.name = CreateSessionOperation
						r.summary = "Create a real-time session"
						r.operationID = "createSession"
						r.operationGroup = ""
						r.pathPattern = "/v1/sessions"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "sessionId"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = EndSessionOperation
							r.summary = "End a session"
							r.operationID = "endSession"
							r.operationGroup = ""
							r.pathPattern = "/v1/sessions/{sessionId}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetSessionOperation
							r.summary = "Get session details"
							r.operationID = "getSession"
							r.operationGroup = ""
							r.pathPattern = "/v1/sessions/{sessionId}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 't': // Prefix: "tts"

				if l := len("tts"); len(elem) >= l && elem[0:l] == "tts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = TextToSpeechOperation
						r.summary = "Text to speech"
						r.operationID = "textToSpeech"
						r.operationGroup = ""
						r.pathPattern = "/v1/tts"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'v': // Prefix: "v"

				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "alidate"

					if l := len("alidate"); len(elem) >= l && elem[0:l] == "alidate" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = ValidateOperation
							r.summary = "Validate API credentials"
							r.operationID = "validate"
							r.operationGroup = ""
							r.pathPattern = "/v1/validate"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'i': // Prefix: "ideos"

					if l := len("ideos"); len(elem) >= l && elem[0:l] == "ideos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							r.name = CreateVideoOperation
							r.summary = "Generate talking video"
							r.operationID = "createVideo"
							r.operationGroup = ""
							r.pathPattern = "/v1/videos"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "videoId"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetVideoOperation
								r.summary = "Get video job status"
								r.operationID = "getVideo"
								r.operationGroup = ""
								r.pathPattern = "/v1/videos/{videoId}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 'o': // Prefix: "oices"

					if l := len("oices"); len(elem) >= l && elem[0:l] == "oices" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListVoicesOperation
							r.summary = "List available voices"
							r.operationID = "listVoices"
							r.operationGroup = ""
							r.pathPattern = "/v1/voices"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'w': // Prefix: "webhooks"

				if l := len("webhooks"); len(elem) >= l && elem[0:l] == "webhooks" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListWebhooksOperation
						r.summary = "List webhooks"
						r.operationID = "listWebhooks"
						r.operationGroup = ""
						r.pathPattern = "/v1/webhooks"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateWebhookOperation
						r.summary = "Create webhook"
						r.operationID = "createWebhook"
						r.operationGroup = ""
						r.pathPattern = "/v1/webhooks"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "webhookId"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteWebhookOperation
							r.summary = "Delete webhook"
							r.operationID = "deleteWebhook"
							r.operationGroup = ""
							r.pathPattern = "/v1/webhooks/{webhookId}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			}

		}
	}
	return r, false
}
