// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateAgentRequest) setDefaults() {
	{
		val := CreateAgentRequestModelType("essence")
		s.ModelType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateEmbedTokenRequest) setDefaults() {
	{
		val := int(3600)
		s.TTLSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TTSRequest) setDefaults() {
	{
		val := string("M1")
		s.VoiceID.SetTo(val)
	}
	{
		val := string("en")
		s.Language.SetTo(val)
	}
}
