// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAgentOperation      OperationName = "CreateAgent"
	CreateEmbedTokenOperation OperationName = "CreateEmbedToken"
	CreateSessionOperation    OperationName = "CreateSession"
	CreateVideoOperation      OperationName = "CreateVideo"
	CreateWebhookOperation    OperationName = "CreateWebhook"
	DeleteAgentOperation      OperationName = "DeleteAgent"
	DeleteWebhookOperation    OperationName = "DeleteWebhook"
	EndSessionOperation       OperationName = "EndSession"
	GetAgentOperation         OperationName = "GetAgent"
	GetBalanceOperation       OperationName = "GetBalance"
	GetSessionOperation       OperationName = "GetSession"
	GetVideoOperation         OperationName = "GetVideo"
	ListAgentsOperation       OperationName = "ListAgents"
	ListVoicesOperation       OperationName = "ListVoices"
	ListWebhooksOperation     OperationName = "ListWebhooks"
	SpeakOperation            OperationName = "Speak"
	TextToSpeechOperation     OperationName = "TextToSpeech"
	UpdateAgentOperation      OperationName = "UpdateAgent"
	UploadFileOperation       OperationName = "UploadFile"
	ValidateOperation         OperationName = "Validate"
)
