// Code generated by ogen, DO NOT EDIT.
package api

type CreateAgentRes interface {
	createAgentRes()
}

type CreateEmbedTokenRes interface {
	createEmbedTokenRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type CreateVideoRes interface {
	createVideoRes()
}

type CreateWebhookRes interface {
	createWebhookRes()
}

type DeleteAgentRes interface {
	deleteAgentRes()
}

type DeleteWebhookRes interface {
	deleteWebhookRes()
}

type EndSessionRes interface {
	endSessionRes()
}

type GetAgentRes interface {
	getAgentRes()
}

type GetBalanceRes interface {
	getBalanceRes()
}

type GetSessionRes interface {
	getSessionRes()
}

type GetVideoRes interface {
	getVideoRes()
}

type ListAgentsRes interface {
	listAgentsRes()
}

type ListVoicesRes interface {
	listVoicesRes()
}

type ListWebhooksRes interface {
	listWebhooksRes()
}

type SpeakRes interface {
	speakRes()
}

type TextToSpeechRes interface {
	textToSpeechRes()
}

type UpdateAgentRes interface {
	updateAgentRes()
}

type UploadFileRes interface {
	uploadFileRes()
}

type ValidateRes interface {
	validateRes()
}
