// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAgent implements createAgent operation.
//
// Generate a new avatar agent from a text prompt with optional image/audio.
// Returns immediately with agent ID; use GET /v1/agents/{id} to poll status.
//
// POST /v1/agents
func (UnimplementedHandler) CreateAgent(ctx context.Context, req *CreateAgentRequest) (r CreateAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEmbedToken implements createEmbedToken operation.
//
// Mint a short-lived JWT for embedding avatar in websites.
//
// POST /v1/embed/token
func (UnimplementedHandler) CreateEmbedToken(ctx context.Context, req *CreateEmbedTokenRequest) (r CreateEmbedTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSession implements createSession operation.
//
// Create a new real-time conversation session with an agent.
// Returns connection details for WebRTC/LiveKit.
//
// POST /v1/sessions
func (UnimplementedHandler) CreateSession(ctx context.Context, req *CreateSessionRequest) (r CreateSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateVideo implements createVideo operation.
//
// Generate an MP4 talking video from text or audio.
// This is an async operation; poll GET /v1/videos/{id} for status.
//
// POST /v1/videos
func (UnimplementedHandler) CreateVideo(ctx context.Context, req *CreateVideoRequest) (r CreateVideoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWebhook implements createWebhook operation.
//
// Create webhook.
//
// POST /v1/webhooks
func (UnimplementedHandler) CreateWebhook(ctx context.Context, req *CreateWebhookRequest) (r CreateWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgent implements deleteAgent operation.
//
// Delete agent.
//
// DELETE /v1/agents/{agentId}
func (UnimplementedHandler) DeleteAgent(ctx context.Context, params DeleteAgentParams) (r DeleteAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWebhook implements deleteWebhook operation.
//
// Delete webhook.
//
// DELETE /v1/webhooks/{webhookId}
func (UnimplementedHandler) DeleteWebhook(ctx context.Context, params DeleteWebhookParams) (r DeleteWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EndSession implements endSession operation.
//
// End a session.
//
// DELETE /v1/sessions/{sessionId}
func (UnimplementedHandler) EndSession(ctx context.Context, params EndSessionParams) (r EndSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgent implements getAgent operation.
//
// Get agent details.
//
// GET /v1/agents/{agentId}
func (UnimplementedHandler) GetAgent(ctx context.Context, params GetAgentParams) (r GetAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBalance implements getBalance operation.
//
// Get account balance.
//
// GET /v1/billing/balance
func (UnimplementedHandler) GetBalance(ctx context.Context) (r GetBalanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSession implements getSession operation.
//
// Get session details.
//
// GET /v1/sessions/{sessionId}
func (UnimplementedHandler) GetSession(ctx context.Context, params GetSessionParams) (r GetSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVideo implements getVideo operation.
//
// Get video job status.
//
// GET /v1/videos/{videoId}
func (UnimplementedHandler) GetVideo(ctx context.Context, params GetVideoParams) (r GetVideoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgents implements listAgents operation.
//
// List all agents.
//
// GET /v1/agents
func (UnimplementedHandler) ListAgents(ctx context.Context, params ListAgentsParams) (r ListAgentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVoices implements listVoices operation.
//
// List available voices.
//
// GET /v1/voices
func (UnimplementedHandler) ListVoices(ctx context.Context) (r ListVoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWebhooks implements listWebhooks operation.
//
// List webhooks.
//
// GET /v1/webhooks
func (UnimplementedHandler) ListWebhooks(ctx context.Context) (r ListWebhooksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Speak implements speak operation.
//
// Send text for the agent to speak with lip-sync.
//
// POST /v1/agents/{agentId}/speak
func (UnimplementedHandler) Speak(ctx context.Context, req *SpeakRequest, params SpeakParams) (r SpeakRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TextToSpeech implements textToSpeech operation.
//
// Convert text to audio using bitHuman TTS.
//
// POST /v1/tts
func (UnimplementedHandler) TextToSpeech(ctx context.Context, req *TTSRequest) (r TextToSpeechRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAgent implements updateAgent operation.
//
// Update agent.
//
// PATCH /v1/agents/{agentId}
func (UnimplementedHandler) UpdateAgent(ctx context.Context, req *UpdateAgentRequest, params UpdateAgentParams) (r UpdateAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadFile implements uploadFile operation.
//
// Upload images, video, audio, or documents.
//
// POST /v1/files
func (UnimplementedHandler) UploadFile(ctx context.Context, req *UploadFileRequest) (r UploadFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Validate implements validate operation.
//
// Cheapest way to verify API key is valid.
//
// POST /v1/validate
func (UnimplementedHandler) Validate(ctx context.Context) (r ValidateRes, _ error) {
	return r, ht.ErrNotImplemented
}
